[package]
name = "pump_fun"
version = "1.0.0"
authors = []

[addresses]
Amm_Dex="0x326cb39974f25c12cc42e942746448c37b9dd13cca84b4de0a9ce67cd5cbd25f"
[dev-addresses]
test_coin = "0x2"
Amm_Dex ="0x1"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
